"""empty message

Revision ID: 7918b877dc73
Revises: 13cd13f1141f
Create Date: 2020-02-08 21:46:55.845796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7918b877dc73'
down_revision = '13cd13f1141f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play', sa.Column('game_dig', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play', 'game_dig')
    # ### end Alembic commands ###
