"""empty message

Revision ID: 80f61f0979a0
Revises: c1bd7fa69c29
Create Date: 2020-02-14 22:09:55.830622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f61f0979a0'
down_revision = 'c1bd7fa69c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game3', sa.Column('s1', sa.Integer(), nullable=True))
    op.add_column('game3', sa.Column('s2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game3', 's2')
    op.drop_column('game3', 's1')
    # ### end Alembic commands ###
