"""play_game play  table

Revision ID: a3b3d154fcf2
Revises: 8f551e185a59
Create Date: 2019-12-22 16:07:39.456881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b3d154fcf2'
down_revision = '8f551e185a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_time', sa.DateTime(), nullable=True),
    sa.Column('game_digit', sa.Integer(), nullable=True),
    sa.Column('game_series', sa.Boolean(), nullable=True),
    sa.Column('game_bet', sa.Integer(), nullable=True),
    sa.Column('game_result', sa.Float(), nullable=True),
    sa.Column('game_win', sa.Boolean(), nullable=True),
    sa.Column('game_stat', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('play_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('game_num', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['play.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_game_timestamp'), 'play_game', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_game_timestamp'), table_name='play_game')
    op.drop_table('play_game')
    op.drop_table('play')
    # ### end Alembic commands ###
