"""empty message

Revision ID: beb249720b87
Revises: 7b0fd250cd7a
Create Date: 2020-01-15 00:24:32.089855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb249720b87'
down_revision = '7b0fd250cd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play', sa.Column('game_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play', 'game_type')
    # ### end Alembic commands ###
